Feat/pat link samples
open-fabric/openfabric-integration-samples pull request #107
Opened 2023-03-21 01:59 UTC by tungd

2023-03-27 05:12 UTC, vinh0604 requested changes

2023-03-27 05:12 UTC, vinh0604 commented on account-integration-sample/controllers/pat.js
> +      url: `${of_pat_url}/v1/preapproved_transaction_links/redirect?link_id=${result.data.id}&status=${status}`
Tenant doesn't need to configure the redirect URL like this, they just need to use the OF gateway redirect URL submitted earlier as is.

2023-03-27 05:12 UTC, vinh0604 commented on account-integration-sample/controllers/pat.js
> +      id: req.body.of_link_ref,
`id` can be removed, as only `tenant_link_ref` is required for approve/decline PAT link.

2023-03-27 05:12 UTC, vinh0604 commented on account-integration-sample/controllers/pat.js
> +    consent_capture_page_url: `http://localhost:4000/pat/consent/${ref}`
`http://localhost:4000` should be parameterized with the actual domain that going to deploy the Tenant samples,

2023-03-27 05:12 UTC, vinh0604 commented on pat-link-sample/src/pages/index.tsx
> +        const transaction = await (
Please rename to `consentRedirectUrl` to better describe the variable value.

2023-03-27 05:12 UTC, vinh0604 commented on pat-link-sample/src/pages/index.tsx
> +        Router.push(transaction);
We should use `window.localtion.href = ...` here to trigger redirect.

2023-03-27 05:12 UTC, vinh0604 commented on script/deploy-template.json
> +      "image": "$MERCHANT_PAT_LINK_IMAGE_NAME",
We also need to update the `deploy.sh` to add this new image to the deployment step.

2023-03-27 10:53 UTC, loiopenfabric commented on pat-link-sample/src/pages/index.tsx
> +        Router.push(transaction);
It does not work

2023-03-27 11:08 UTC, vinh0604 commented on pat-link-sample/src/pages/index.tsx
> +        Router.push(transaction);
Please try 
```ts
const transaction = await (
  await fetch("/api/link", ...)
).json();

window.location.href = transaction.url;
```

2023-03-28 04:18 UTC, vinh0604 approved these changes
LGTM

2023-03-28 04:18 UTC, merged