Feat/tenant initiated pat creation
open-fabric/openfabric-integration-samples pull request #160
Opened 2023-11-21 08:43 UTC by AbrahamOEd

2023-11-22 05:07 UTC, AbrahamOEd commented
## Tenant Pat Create Success Page (return_url)
<img width="1331" alt="Screenshot 2023-11-21 at 4 41 55 PM" src="https://github.com/open-fabric/openfabric-integration-samples/assets/125857654/9b249b21-f151-479e-bd78-52a50f36d873">

2023-11-22 05:07 UTC, AbrahamOEd commented
## Tenant Pat Creation page
<img width="1152" alt="Screenshot 2023-11-21 at 4 39 36 PM" src="https://github.com/open-fabric/openfabric-integration-samples/assets/125857654/1f6d0e08-7717-4eb0-a22f-18101c8ebcc0">

2023-11-22 05:08 UTC, AbrahamOEd commented
## Partner onboarding page, which redirects to gateway 
<img width="1248" alt="Screenshot 2023-11-21 at 4 39 04 PM" src="https://github.com/open-fabric/openfabric-integration-samples/assets/125857654/742e332b-d515-4435-a9dd-89d057302c11">
<img width="1066" alt="Screenshot 2023-11-21 at 4 39 10 PM" src="https://github.com/open-fabric/openfabric-integration-samples/assets/125857654/7de754f4-d2fa-4702-abe9-c6b87b070619">

2023-11-22 07:09 UTC, vinh0604 requested changes

2023-11-22 07:09 UTC, vinh0604 commented on account-integration-sample/controllers/pat.js
> +        tenant_partner_ref: data.tenant_partner_ref,
This should come from environment variable, i.e. preconfiguring on server instead of taken from request

2023-11-22 07:09 UTC, vinh0604 commented on pat-link-sample/README.md
> +OF_GATEWAY_REDIRECT_URL=
This should not be required, instead Partner should taken the url from OpenFabric incoming request.

2023-11-22 07:09 UTC, vinh0604 commented on pat-link-sample/src/lib/config.ts
> +export const OF_GATEWAY_REDIRECT_URL = process.env.OF_GATEWAY_REDIRECT_URL || 'https://gateway.dev.openfabric.co/pat/redirect'
Same as above

2023-11-22 07:09 UTC, vinh0604 commented on script/build.sh
> +  --build-arg OF_GATEWAY_REDIRECT_URL=${OF_GATEWAY_REDIRECT_URL} \
Same as above

2023-11-22 07:09 UTC, vinh0604 commented on script/deploy-template.json
> +      "environment": {
Same as above

2023-11-22 07:09 UTC, vinh0604 commented on pat-link-sample/src/pages/onboarding.tsx
> +export default function Onboarding() {
We would need to have an sample Partner API for OF to call to submit link details.
This API would persist the link details in the local db, including the gateway redirect URL, generate the onboarding url (which point to this page)
This page should display the link details, and on submit, should redirect to the submitted gateway redirect url, instead of hard-coding it here.

2023-11-22 07:34 UTC, AbrahamOEd commented on account-integration-sample/controllers/pat.js
> +        return_url: data.returl_url,
its hard coded on the frontend side

2023-11-22 10:30 UTC, AbrahamOEd commented on pat-link-sample/src/pages/onboarding.tsx
> +export default function Onboarding() {
<img width="1034" alt="Screenshot 2023-11-22 at 6 30 25 PM" src="https://github.com/open-fabric/openfabric-integration-samples/assets/125857654/3c9fba1f-c7b9-4ee0-b70b-4f671de1eb76">

2023-11-23 02:56 UTC, vinh0604 requested changes

2023-11-23 02:56 UTC, vinh0604 commented on account-integration-sample/controllers/pat.js
> +        tenant_partner_ref: crypto.randomUUID(),
This should not be auto-generated, but need to be pre-configured, e.g. taken from env var, as it is used to identify the respective Partner

2023-11-23 02:56 UTC, vinh0604 commented on pat-link-sample/src/lib/core.ts
> +  customer_billing_address: {
Can change to `billing_address` for consistent

2023-11-23 02:56 UTC, vinh0604 commented on pat-link-sample/src/pages/api/pat_link.ts
> +  customer_billing_address: {
Can change to `billing_address` for consistent

2023-11-23 02:56 UTC, vinh0604 commented on pat-link-sample/src/pages/api/pat_link.ts
> +      customer_billing_address: data.customer_billing_address,
Same as above

2023-11-23 02:56 UTC, vinh0604 commented on pat-link-sample/src/pages/onboarding.tsx
> +export default function Onboarding() {
Please format it a bit to be similar to the following: 
![image](https://github.com/open-fabric/openfabric-integration-samples/assets/886778/edadd1e0-030b-40a5-90f7-6dde8d77a2bf)

2023-11-23 06:36 UTC, AbrahamOEd commented
<img width="1144" alt="Screenshot 2023-11-23 at 2 36 18 PM" src="https://github.com/open-fabric/openfabric-integration-samples/assets/125857654/e2659db2-c7c0-4bcc-8b80-57883579b5d3">

2023-11-23 07:57 UTC, merged